image: circleci/openjdk:11-jdk-browsers

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
cache:
    key: m2-cache
    paths:
      - .m2/

stages:
  - build
  - test
  - deploy
  
build: &build
  stage: build
  script:
    - mvn compile -DskipTests -s settings.xml
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^(production|stage)-.+/
      
build-commit:
  <<: *build
  only:
    refs:
      - branches
  
      
test: &test
  stage: test
  script:
    - mvn test -s settings.xml
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^(production|stage)-.+/
      
test-commit:
  <<: *test
  only:
    refs:
      - branches
  
 
deploy-stage: &deploy
  stage: deploy
  script:
    - mvn package -s settings.xml -DskipTests
    - ./deploy/stage.sh
  environment:
    name: stage/$CI_COMMIT_TAG
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^stage-.+/

deploy-production:
  <<: *deploy
  stage: deploy
  script:
    - mvn package -s settings.xml -DskipTests
    - ./deploy/production.sh
  environment:
    name: production/$CI_COMMIT_TAG
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^production-.+/
