version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:8.0.15
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=trading_bots
      - MYSQL_DATABASE=trading_bots
      - MYSQL_USER=usr_trading_bots
      - MYSQL_PASSWORD=trading_bots